kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
      minVersion: 4.18.6
      maxVersion: 4.18.6
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
      full: false
      packages:
        - name: node-maintenance-operator
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.18
      full: false
      packages:
        - name: crunchy-postgres-operator
  additionalImages:
   - name: registry.access.redhat.com/ubi9/ubi:latest
   - name: registry.access.redhat.com/ubi9/toolbox:latest
