kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      type: ocp
      minVersion: 4.18.6
      maxVersion: 4.18.6
    graph: true
  operators: []
  additionalImages: []
